-- 人员相关
DROP TABLE IF EXISTS laagenttemp;
/*==============================================================*/
/* Table: LAAGENTTEMP                                         */
/*==============================================================*/
CREATE TABLE laagenttemp
(
    agentcode                VARCHAR(10) NOT NULL COMMENT '代理人编码',
    agentgroup               VARCHAR(12) COMMENT '代理人展业机构代码',
    managecom                VARCHAR(8) COMMENT '管理机构',
    password                 VARCHAR(40) COMMENT '密码',
    entryno                  VARCHAR(20) COMMENT '推荐报名编号',
    name                     VARCHAR(20) NOT NULL COMMENT '姓名',
    sex                      VARCHAR(1)  NOT NULL COMMENT '性别',
    birthday                 DATE        NOT NULL COMMENT '出生日期',
    nativeplace              VARCHAR(3) COMMENT '籍贯',
    nationality              VARCHAR(3) COMMENT '民族',
    marriage                 VARCHAR(1) COMMENT '婚姻状况',
    creditgrade              VARCHAR(1) COMMENT '信用等级',
    homeaddresscode          VARCHAR(10) COMMENT '家庭地址编码',
    homeaddress              VARCHAR(80) COMMENT '家庭地址',
    postaladdress            VARCHAR(80) COMMENT '通讯地址',
    zipcode                  VARCHAR(6) COMMENT '邮政编码',
    phone                    VARCHAR(18) COMMENT '电话',
    bp                       VARCHAR(20) COMMENT '传呼',
    mobile                   VARCHAR(15) COMMENT '手机',
    email                    VARCHAR(50) COMMENT '邮箱',
    marriagedate             DATE COMMENT '结婚日期',
    idno                     VARCHAR(20) COMMENT '身份证号码',
    source                   VARCHAR(100) COMMENT '来源地',
    bloodtype                VARCHAR(2) COMMENT '血型',
    polityvisage             VARCHAR(4) COMMENT '政治面貌',
    degree                   VARCHAR(1) COMMENT '学历',
    graduateschool           VARCHAR(40) COMMENT '毕业院校',
    speciality               VARCHAR(40) COMMENT '专业',
    posttitle                VARCHAR(2) COMMENT '职称',
    foreignlevel             VARCHAR(2) COMMENT '外语水平',
    workage                  INT COMMENT '从业年限',
    oldcom                   VARCHAR(40) COMMENT '原工作单位',
    oldoccupation            VARCHAR(20) COMMENT '原职业',
    headship                 VARCHAR(30) COMMENT '工作职务',
    recommendagent           VARCHAR(10) COMMENT '推荐代理人',
    business                 VARCHAR(20) COMMENT '工种/行业',
    salequaf                 VARCHAR(1) COMMENT '销售资格',
    quafno                   VARCHAR(30) COMMENT '代理人资格证号码',
    quafstartdate            DATE COMMENT '证书开始日期',
    quafenddate              DATE COMMENT '证书结束日期',
    devno1                   VARCHAR(30) COMMENT '展业证号码1',
    devno2                   VARCHAR(20) COMMENT '展业证号码2',
    retaincontno             VARCHAR(20) COMMENT '聘用合同号码',
    agentkind                VARCHAR(6) COMMENT '代理人类别',
    devgrade                 VARCHAR(2) COMMENT '业务拓展级别',
    insideflag               VARCHAR(1) COMMENT '内勤标志',
    fulltimeflag             VARCHAR(1) COMMENT '是否专职标志',
    noworkflag               VARCHAR(1) COMMENT '是否有待业证标志',
    traindate                DATE COMMENT '档案调入日期',
    employdate               DATE COMMENT '录用日期',
    indueformdate            DATE COMMENT '转正日期',
    outworkdate              DATE COMMENT '离司日期',
    recommendno              VARCHAR(20) COMMENT '推荐名编号2',
    cautionername            VARCHAR(20) COMMENT '担保人名称',
    cautionersex             VARCHAR(2) COMMENT '担保人性别',
    cautionerid              VARCHAR(20) COMMENT '担保人身份证',
    cautionerbirthday        DATE COMMENT '担保人出生日期',
    approver                 VARCHAR(10) COMMENT '复核员',
    approvedate              DATE COMMENT '复核日期',
    assumoney                DECIMAL(12, 2) COMMENT '保证金',
    remark                   VARCHAR(80) COMMENT '备注',
    agentstate               VARCHAR(2) COMMENT '代理人状态',
    qualipassflag            VARCHAR(1) COMMENT '档案标志位',
    smokeflag                VARCHAR(1) COMMENT '打折标志',
    rgtaddress               VARCHAR(20) COMMENT '户口所在地',
    bankcode                 VARCHAR(20) COMMENT '银行编码',
    bankaccno                VARCHAR(20) COMMENT '银行账户',
    branchtype               VARCHAR(2)  NOT NULL COMMENT '展业类型',
    trainperiods             VARCHAR(8) COMMENT '培训期数',
    branchcode               VARCHAR(12) COMMENT '代理人组别',
    age                      INT COMMENT '代理人年龄',
    channelname              VARCHAR(100) COMMENT '所属渠道',
    receiptno                VARCHAR(30) COMMENT '保证金收据号',
    idnotype                 VARCHAR(2) COMMENT '证件号码类型',
    branchtype2              VARCHAR(2) COMMENT '子渠道',
    trainpassflag            VARCHAR(1) COMMENT '培训通过标记',
    negreason                VARCHAR(2) COMMENT '未进入系统原因',
    emergentlink             VARCHAR(10) COMMENT '紧急联系人',
    emergentphone            VARCHAR(20) COMMENT '紧急联系人电话',
    retainstartdate          DATE COMMENT '劳动合同开始日期',
    retainenddate            DATE COMMENT '劳动合同截止日期',
    togaeflag                VARCHAR(1) COMMENT '司服是否领取标志',
    archievecode             VARCHAR(20) COMMENT '档案编码',
    comage                   INT COMMENT '司龄',
    busiage                  INT COMMENT '职龄',
    serviceage               INT COMMENT '工龄',
    fortes                   VARCHAR(20) COMMENT '特长',
    hobbies                  VARCHAR(20) COMMENT '爱好',
    agentsource              VARCHAR(2) COMMENT '来源',
    violation                VARCHAR(1) COMMENT '是否有违规违纪记录',
    foreven                  VARCHAR(1) COMMENT '是否有投连销售资格',
    acctype                  VARCHAR(1) COMMENT '对公对私标识',
    bankaccprovince          VARCHAR(120) COMMENT '开户行省',
    bankacccity              VARCHAR(120) COMMENT '开户市',
    accattributes            VARCHAR(1) COMMENT '卡折类型',
    bankaccsub               VARCHAR(200) COMMENT '开户行细分',
    worknature               VARCHAR(2) COMMENT '工作性质',
    employmentnature         VARCHAR(2)  DEFAULT NULL COMMENT '用工性质',
    supervisiontel           VARCHAR(50) DEFAULT NULL COMMENT '保险行业协会监督电话',
    practiceregistrationmark VARCHAR(1)  DEFAULT NULL COMMENT '执业登记标志',
    breedbenefit             VARCHAR(1) COMMENT '是否享受育成利益',
    addbenefit               VARCHAR(1) COMMENT '是否享受增员利益',
    insurancecertificate     VARCHAR(1) COMMENT '是否有分红保险及万能保险销售资质证书',
    investment               VARCHAR(1) COMMENT '是否有投资连结保险及变额年金保险销售资质证书',
    operator                 VARCHAR(60) NOT NULL COMMENT '操作员',
    makedate                 DATE        NOT NULL COMMENT '入机日期',
    maketime                 VARCHAR(8)  NOT NULL COMMENT '入机时间',
    modifyoperator           VARCHAR(20) NOT NULL COMMENT '最后一次修改人',
    modifydate               DATE        NOT NULL COMMENT '最后一次修改日期',
    modifytime               VARCHAR(8)  NOT NULL COMMENT '最后一次修改时间',
    PRIMARY KEY (agentcode),
    KEY `idx_laagenttemp_index1` (`branchtype`),
    KEY `idx_laagenttemp_index2` (`managecom`),
    KEY `idx_laagenttemp_index3` (`agentgroup`),
    KEY `idx_laagenttemp_index4` (`idno`),
    KEY `idx_laagenttemp_index5` (`mobile`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE utf8mb4_general_ci COMMENT ='销管代理人入职申请信息表';
