-- 第三方人员相关表
DROP TABLE IF EXISTS lasaleagent;
/*==============================================================*/
/* Table: LASALEAGENT                                           */
/*==============================================================*/
CREATE TABLE lasaleagent
(
    salecode       VARCHAR(20) NOT NULL COMMENT '中介销售人员编码',
    agentcom       VARCHAR(20) COMMENT '经代公司编码',
    managecom      VARCHAR(8) COMMENT '管理机构编码',
    oldsalecode    VARCHAR(30) COMMENT '原经代公司销售人员编码',
    name           VARCHAR(20) COMMENT '姓名',
    sex            VARCHAR(1) COMMENT '性别',
    employdate     DATE COMMENT '录用日期',
    outworkdate    DATE COMMENT '不可修改，由行政信息提供',
    agentstate     VARCHAR(2) COMMENT '01－在职，02－二次增员，03－准离职,04-离职',
    birthday       DATE COMMENT '出生日期',
    nativeplace    VARCHAR(3) COMMENT '籍贯',
    nationality    VARCHAR(3) COMMENT '民族',
    marriage       VARCHAR(1) COMMENT '婚姻状态',
    postaladdress  VARCHAR(80) COMMENT '通讯地址',
    zipcode        VARCHAR(6) COMMENT '邮政编码',
    phone          VARCHAR(18) COMMENT '电话',
    bp             VARCHAR(20) COMMENT '传呼',
    mobile         VARCHAR(15) COMMENT '手机',
    email          VARCHAR(50) COMMENT '邮箱',
    idno           VARCHAR(20) COMMENT '身份证号',
    source         VARCHAR(100) COMMENT '来源',
    polityvisage   VARCHAR(4) COMMENT '政治面貌',
    degree         VARCHAR(1) COMMENT '0-博士以上1-硕士2-大本3-大专4-中专5-高中',
    graduateschool VARCHAR(40) COMMENT '毕业院校',
    speciality     VARCHAR(40) COMMENT '专业',
    posttitle      VARCHAR(2) COMMENT '职称',
    foreignlevel   VARCHAR(2) COMMENT '外语水平',
    workage        INT COMMENT '从业年限',
    oldcom         VARCHAR(40) COMMENT '原工作单位',
    oldoccupation  VARCHAR(20) COMMENT '原职务',
    headship       VARCHAR(30) COMMENT '工作职务（体制）',
    emergentlink   VARCHAR(10) COMMENT '紧急联系人',
    emergentphone  VARCHAR(20) COMMENT '紧急联系电话',
    salequaf       VARCHAR(1) COMMENT '销售资格',
    quafno         VARCHAR(20) COMMENT '资格证号码',
    quafstartdate  DATE COMMENT '证书开始日期',
    quafenddate    DATE COMMENT '证书结束日期',
    devno1         VARCHAR(30) COMMENT '展业证号码1',
    devno2         VARCHAR(30) COMMENT '展业证号码2',
    agentkind      VARCHAR(6) COMMENT '代理人种类',
    rgtaddress     VARCHAR(20) COMMENT '户口所在地',
    busiage        INT COMMENT '职龄',
    bankaccno      VARCHAR(20) COMMENT '银行账号',
    branchtype     VARCHAR(2)  NOT NULL COMMENT '渠道类型',
    age            INT COMMENT '年龄',
    idnotype       VARCHAR(2) COMMENT '证件类型',
    branchtype2    VARCHAR(2) COMMENT '分支类型',
    delaydate      VARCHAR(10) COMMENT '资格证延长天数',
    f1             VARCHAR(20) COMMENT '备用字段1',
    f2             VARCHAR(20) COMMENT '备用字段2',
    f3             DATE COMMENT '备用字段3',
    f4             DATE COMMENT '备用字段4',
    f5             VARCHAR(20) COMMENT '备用字段5',
    operator       VARCHAR(60) NOT NULL COMMENT '操作员',
    makedate       DATE        NOT NULL COMMENT '入机日期',
    maketime       VARCHAR(8)  NOT NULL COMMENT '入机时间',
    modifydate     DATE        NOT NULL COMMENT '最后一次修改日期',
    modifytime     VARCHAR(8)  NOT NULL COMMENT '最后一次修改时间',
    modifyoperator VARCHAR(20) NOT NULL COMMENT '最后一次修改人',
    PRIMARY KEY (salecode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci COMMENT='销管中介人员信息表';

DROP TABLE IF EXISTS lasaleagentb;
/*==============================================================*/
/* Table: lasaleagentb                                 */
/*==============================================================*/
CREATE TABLE lasaleagentb
(
    edorno           VARCHAR(20) NOT NULL COMMENT '转储号',
    edortype         VARCHAR(2)  NOT NULL COMMENT '01-考核结果, 02-机构调整, 03-人员调动, 04-二次增员, 05-原始修改备份, 06-轨迹修改备份（育成关系，所属关系）, 07-主管任命修改, 10-业务员转收费员',
    salecode         VARCHAR(20) NOT NULL COMMENT '中介销售人员编码',
    agentcom         VARCHAR(20) COMMENT '经代公司编码',
    managecom        VARCHAR(8) COMMENT '管理机构编码',
    oldsalecode      VARCHAR(30) COMMENT '原经代公司销售人员编码',
    name             VARCHAR(20) COMMENT '姓名',
    sex              VARCHAR(1) COMMENT '性别',
    employdate       DATE COMMENT '录用日期',
    outworkdate      DATE COMMENT '不可修改，由行政信息提供',
    agentstate       VARCHAR(2) COMMENT '01－在职， 02－二次增员， 03－准离职, 04-离职',
    birthday         DATE COMMENT '出生日期',
    nativeplace      VARCHAR(3) COMMENT '籍贯',
    nationality      VARCHAR(3) COMMENT '民族',
    marriage         VARCHAR(1) COMMENT '婚姻状态',
    postaladdress    VARCHAR(80) COMMENT '通讯地址',
    zipcode          VARCHAR(6) COMMENT '邮政编码',
    phone            VARCHAR(18) COMMENT '电话',
    bp               VARCHAR(20) COMMENT '传呼',
    mobile           VARCHAR(15) COMMENT '手机',
    email            VARCHAR(50) COMMENT '邮箱',
    idno             VARCHAR(20) COMMENT '身份证号',
    source           VARCHAR(100) COMMENT '来源',
    polityvisage     VARCHAR(4) COMMENT '政治面貌',
    degree           VARCHAR(1) COMMENT '0-博士以上, 1-硕士, 2-大本, 3-大专, 4-中专, 5-高中',
    graduateschool   VARCHAR(40) COMMENT '毕业院校',
    speciality       VARCHAR(40) COMMENT '专业',
    posttitle        VARCHAR(2) COMMENT '职称',
    foreignlevel     VARCHAR(2) COMMENT '外语水平',
    workage          INT COMMENT '从业年限',
    oldcom           VARCHAR(40) COMMENT '原工作单位',
    oldoccupation    VARCHAR(20) COMMENT '原职务',
    headship         VARCHAR(30) COMMENT '工作职务（体制）',
    emergentlink     VARCHAR(10) COMMENT '0-通过, 1-未通过',
    emergentphone    VARCHAR(20) COMMENT '0-通过, 1-未通过',
    salequaf         VARCHAR(1) COMMENT 'Y/N',
    quafno           VARCHAR(20) COMMENT '资格证号码',
    quafstartdate    DATE COMMENT '证书开始日期',
    quafenddate      DATE COMMENT '证书结束日期',
    devno1           VARCHAR(30) COMMENT '展业证号码1',
    devno2           VARCHAR(30) COMMENT '展业证号码2',
    agentkind        VARCHAR(6) COMMENT '01-银代经理, 02-银代协理, 03-渠道经理, 04-银代客户经理, 05-培训岗, 06-企划策划岗, 07-销售支援岗, 08-综合岗, 10-普通代理人, 11-组主管, 12-部主管, 13-督导长, 14-区域督导长, 20-法人客户经理, 21-法人组经理, 22-法人协理, 23－法人部经理, 24-培训岗, 25-企划策划岗, 26-销售支援岗, 27-综合岗',
    rgtaddress       VARCHAR(20) COMMENT '户口所在地',
    busiage          INT COMMENT '职龄',
    bankaccno        VARCHAR(20) COMMENT '银行账号',
    branchtype       VARCHAR(2)  NOT NULL COMMENT '1-个人代理， 2-团体代理， 3－银行代理， 4－收费员， 5－直销, 9－其他',
    age              INT COMMENT '年龄',
    idnotype         VARCHAR(2) COMMENT '0－身份证 1－护照 2－军官证 3－台胞证 8－其他',
    branchtype2      VARCHAR(2) COMMENT '01 or null -直销, 02-中介, 03-交叉销售',
    delaydate        VARCHAR(10) COMMENT '资格证延长天数',
    f1               VARCHAR(20) COMMENT 'F1',
    f2               VARCHAR(20) COMMENT 'F2',
    f3               DATE COMMENT 'F3',
    f4               DATE COMMENT 'F4',
    f5               VARCHAR(20) COMMENT 'F5',
    operator         VARCHAR(60) NOT NULL COMMENT '操作人员',
    makedate         DATE        NOT NULL COMMENT '入机日期',
    maketime         VARCHAR(8)  NOT NULL COMMENT '入机时间',
    modifydate       DATE        NOT NULL COMMENT '最后一次修改日期',
    modifytime       VARCHAR(8)  NOT NULL COMMENT '最后一次修改时间',
    modifyoperator   VARCHAR(60) not null comment '最后一次修改人',
    lastoperator     VARCHAR(60) COMMENT '备份人',
    lastmakedatetime DATETIME DEFAULT NULL COMMENT '备份时间',
    PRIMARY KEY (edorno)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci COMMENT='销售中介人员信息备份表';




